baseURL = "https://www.letraspara-nick.com"
languageCode = "pt"
title = "Letras para Nick"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
posts = "/:slug/"

[taxonomies]
  tag = "tags"

[params]
  isMobile = "<script>document.write(siteParams.isMobile)</script>"