baseURL = "https://www.letraspara-nick.com"
languageCode = "pt"
title = "Letras para Nick"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
