baseURL = "https://ltsprnk.vercel.app"
languageCode = "pt"
title = "Letras para Nick"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
posts = "/:slug/"

[taxonomies]
  tag = "tags"