baseURL = "https://prollad99.github.io/ltsprnk/"
languageCode = "pt"
title = "Letras para Nick"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
